@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant "lr:ListRoleCommand" as ListRoleCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list r/player")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("list r/player")
activate AddressBookParser

create ListCommandParser
AddressBookParser -> ListCommandParser
activate ListCommandParser

ListCommandParser --> AddressBookParser
deactivate ListCommandParser

AddressBookParser -> ListCommandParser : parse(" r/player")
activate ListCommandParser

create ListRoleCommand
ListCommandParser -> ListRoleCommand
activate ListRoleCommand

ListRoleCommand --> ListCommandParser
deactivate ListRoleCommand

ListCommandParser --> AddressBookParser : lr
deactivate ListCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ListCommandParser -[hidden]-> AddressBookParser
destroy ListCommandParser

AddressBookParser --> LogicManager : lr
deactivate AddressBookParser

LogicManager -> ListRoleCommand : execute(m)
activate ListRoleCommand

ListRoleCommand -> Model : updateFilteredPersonList(rolePredicate)
activate Model
Model --> ListRoleCommand
deactivate Model

create CommandResult
ListRoleCommand -> CommandResult
activate CommandResult
CommandResult --> ListRoleCommand
deactivate CommandResult

ListRoleCommand --> LogicManager : r
deactivate ListRoleCommand

[<--LogicManager
deactivate LogicManager
@enduml
